// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nytpxhcxzswgcbhegthn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55dHB4aGN4enN3Z2NiaGVndGhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1NDQ5MzQsImV4cCI6MjA1NDEyMDkzNH0.ufwVi2_AYjxYM7-8FzdoAQKdivHeetCr9-gQZwMN5so";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);