// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdkxqddwccqxfwysclke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdka3hxZGR3Y2NxeGZ3eXNjbGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2ODA5NzIsImV4cCI6MjA2MTI1Njk3Mn0.c2qKwXuEWu1YuIYV1ZBuP6a8ad-s3UJu_DfPwoiU8V4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);